Get https:/be.myporfolio.io.vn/users

###

Get http://localhost:8080/users/67ee136aecaae2d703767513

###
POST http://localhost:8080/users/add
Content-Type: application/json

{
    "name": "Lê Hoàng Giang",
    "age": 20,
    "email": "crglh25@gmail.com",
    "address": "Đồng Nai"
}
###

PUT  http://localhost:8080/users/update/67ee136aecaae2d703767513
Content-Type: application/json

{
    "name": "Nguyễn Văn Hoàng",
    "age": 20,
    "email": "siro@gmail.com",
    "address": "TPHCM"
}
### 
DELETE http://localhost:8080/users/delete/67ee00f6dde653739d16b974

### posts
GET  http://localhost:8080/posts

###
GET http://localhost:8080/posts/67ef681f8e17ece93077c088

###
POST http://localhost:8080/posts/add
Content-Type: application/json

{
    "title": "Cach ngu 4h trong 2h",
    "content": "Toi se huong dan ban cach ngu 2 h trong 81243 h voi 2 li do sau day",
    "author": "67ee1531e84d9b6562ec17c5"
}
###
DELETE http://localhost:8080/posts/delete/67ef681f8e17ece93077c088

###
PUT  http://localhost:8080/posts/update/67ef691a2f5e05992c6e3aa5
Content-Type: application/json

{
    "title": "Premium cach ngu 8h trong 2h",
    "content": "nay toi se huong dan manh hon",
    "author": "67ee136aecaae2d703767513"
}


###transaction

POST https://be.myporfolio.io.vn/transactions/api/add
Content-Type: application/json

{
  "accountNumber": "123456787",
  "name": "Nguyen Van A",
  "date": "2025-04-15T12:30:00.000Z",
  "amount": 200000,
  "message": "Ung ho nguoi ngheo"
}
###
GET https://be.myporfolio.io.vn/transactions?page=3


###
POST https://be.myporfolio.io.vn/animals/add
Content-Type: application/json

{
  "animalName": "Tê Tê",
  "subtitle": "Loài có vú bị săn nhiều nhất trên thế giới",
  "videoDescription": "https://www.youtube.com/watch?v=Frn-vX8yCMQ",
  "animalInfoHtml": "",
  "threatInfoHtml": "",
  "hunted": true,
  "rescueData": {
    "rescued": 5,
    "recoveryProcess": "~ 60%"
  },
  "sponsorImages": [
    "https://media.istockphoto.com/id/512292162/vi/anh/t%C3%AA-t%C3%AA-s%C4%83n-ki%E1%BA%BFn.jpg?s=612x612&w=0&k=20&c=mDMJchgJ52R86t_HDJlB0Lh-q9blyBH1nlGTW4mVj_4=",
    "https://www.thiennhien.net/wp-content/uploads/2019/12/191219_Pangolin.jpg",
    "https://ik.imagekit.io/tvlk/blog/2024/10/te-te-1-1024x682.jpeg?tr=q-70,c-at_max,w-500,h-300,dpr-2",
    "https://cdn.baoquocte.vn/stores/news_dataimages/minhhoa/042017/06/22/220231_Untitled.jpg"
  ]
}
###
GET https://be.myporfolio.io.vn/animals


###
GET https://be.myporfolio.io.vn/animals/67fe88b47e31ffeb4e94f0c2